on:
  push:
    branches:
      - dev

name: Build and Deploy a Container
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  SERVICE: aegis-alpine-dev
  REGION: asia-east1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true # Set to true to authenticate the Cloud Run action

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build ./ -t asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/aegis/aegis-alpine-dev:${{ github.sha }}
          docker push asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/aegis/aegis-alpine-dev:${{ github.sha }}
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          image: asia-southeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/aegis/aegis-alpine-dev:${{ github.sha }}
          region: ${{ env.REGION }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
